---

- name: install rbenv requirements
  when: ansible_pkg_mgr == "apt"
  become: yes
  apt:
    name: "{{ item.name }}"
  loop:
    - name: libssl-dev
    - name: libreadline-dev
    - name: zlib1g-dev
